In [1]:
import pandas as pd
import numpy as np

### Dataset Relationships
These files use two main identifiers: `tconst` for titles and `nconst` for people. `title.basics.tsv` is the central title lookup, while `name.basics.tsv` is the central person lookup. `title.ratings.tsv` and `title.crew.tsv` add title-level details through `tconst`, and `title.principals.tsv` links titles to people through both `tconst` and `nconst`.

### `name.basics.tsv` - People
This table stores one row per person using `nconst` as the person identifier. It connects to `title.principals.tsv` through `nconst`, and its `knownForTitles` values also reference title IDs (`tconst`) from `title.basics.tsv`.

In [2]:
name_basic = pd.read_csv('raw_data/name.basics.tsv', sep='\t', nrows=1000, skiprows=10000, names=['nconst', 'primaryName', 'birthYear', 'deathYear', 'primaryProfession', 'knownForTitles'])

In [20]:
name_basic.tail(10)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
990,nm0000992,Billie Burke,1884,1970,"actress,soundtrack,archive_footage","tt0032138,tt0023948,tt0030442,tt0034303"
991,nm0000993,Carol Burnett,1933,\N,"actress,producer,writer","tt0061240,tt0083564,tt0105017,tt0082405"
992,nm0000994,Raymond Burr,1917,1993,"actor,production_manager,director","tt0047396,tt0061266,tt0197521,tt0087344"
993,nm0000995,Ellen Burstyn,1932,\N,"actress,producer,director","tt0180093,tt0071115,tt0070047,tt0067328"
994,nm0000996,LeVar Burton,1957,\N,"actor,director,producer","tt0111280,tt0117731,tt0120844,tt0253754"
995,nm0000997,Gary Busey,1944,\N,"actor,producer,composer","tt0077280,tt0093409,tt0102685,tt0105690"
996,nm0000998,Jake Busey,1971,\N,"actor,producer,music_department","tt0120201,tt4574334,tt0116365,tt0120660"
997,nm0000999,Red Buttons,1919,2006,"actor,writer,miscellaneous","tt0050933,tt0076538,tt0069113,tt0056059"
998,nm0001000,Tom Byron,1961,\N,"actor,director,producer","tt2059288,tt0178845,tt0097039,tt0234068"
999,nm0001001,James Caan,1940,2022,"actor,director,stunts","tt0083190,tt0073631,tt0100157,tt0068646"

### `title.basics.tsv` - Titles
This is the central title table: each movie, short, episode, or series is identified by `tconst`. Other title-level tables, such as ratings, crew, and principals, link back to this table using the same `tconst` key.

In [ ]:
title_basic = pd.read_csv('raw_data/title.basics.tsv', sep='\t', nrows=1000, skiprows=10000, names=['tconst', 'titleType', 'primaryTitle', 'originalTitle', 'isAdult', 'startYear', 'endYear', 'runtimeMinutes', 'genres'])

In [22]:
title_basic.tail(10)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
990,tt0011153,movie,En la hacienda,En la hacienda,0,1922,\N,\N,Drama
991,tt0011154,movie,Los enmascarados de Mazatlán,Los enmascarados de Mazatlán,0,1920,\N,\N,"Action,Adventure,Drama"
992,tt0011155,movie,Entgleist,Entgleist,0,1921,\N,\N,\N
993,tt0011156,short,Entierro de las víctimas del cuartel del Carmen,Entierro de las víctimas del cuartel del Carmen,0,1920,\N,\N,"Documentary,Short"
994,tt0011157,movie,Erotikon,Erotikon,0,1920,\N,106,"Comedy,Romance"
995,tt0011158,short,La escuadra en el puerto,La escuadra en el puerto,0,1920,\N,1,"Documentary,Short"
996,tt0011159,movie,The Scandal,El escándalo,0,1920,\N,\N,Drama
997,tt0011160,movie,El espectro del castillo,El espectro del castillo,0,1920,\N,\N,\N
998,tt0011161,movie,Everything But the Truth,Everything But the Truth,0,1920,\N,50,Comedy
999,tt0011162,movie,The Evil Eye,The Evil Eye,0,1920,\N,\N,Action

### `title.crew.tsv` - Directors and Writers
This table lists the main directors and writers for each title. It relates to `title.basics.tsv` by `tconst`; the comma-separated `directors` and `writers` fields contain person IDs (`nconst`) that can be matched to `name.basics.tsv`.

In [3]:
title_crew = pd.read_csv('raw_data/title.crew.tsv', sep='\t', nrows=1000, skiprows=10000, names=['tconst', 'directors', 'writers'])

In [24]:
title_crew

        tconst            directors              writers
0    tt0010142            nm0398464  nm0398464,nm0765716
1    tt0010143            nm0288616  nm0191643,nm0288616
2    tt0010144            nm0043018                   \N
3    tt0010145            nm0513617            nm0000485
4    tt0010146  nm0332531,nm0730018  nm0907778,nm0516001
..         ...                  ...                  ...
995  tt0011158            nm0655287                   \N
996  tt0011159            nm0194098                   \N
997  tt0011160            nm0796636            nm0796636
998  tt0011161  nm0529047,nm0602905  nm0291408,nm0403527
999  tt0011162  nm0178107,nm0888428            nm0564946

[1000 rows x 3 columns]

### `title.principals.tsv` - Main Credits
This table records the principal cast and crew for each title, with one row per credited person and role. It connects titles through `tconst` and people through `nconst`, making it the main bridge between `title.basics.tsv` and `name.basics.tsv`.

In [ ]:
title_principals = pd.read_csv('raw_data/title.principals.tsv', sep='\t', nrows=1000, skiprows=10000, names=['tconst', 'ordering', 'nconst', 'category', 'job', 'characters'])

In [26]:
title_principals

,tconst,ordering,nconst,category,job,characters
0,tt0001733,8,nm0125164,actor,\N,"[""One of the Father's Friends""]"
1,tt0001733,9,nm0187981,actor,\N,\N
2,tt0001733,10,nm0424530,actor,\N,\N
3,tt0001733,11,nm0000428,director,\N,\N
4,tt0001733,12,nm0005658,cinematographer,\N,\N
...,...,...,...,...,...,...
995,tt0001894,4,nm0639631,actor,\N,"[""The Opponent""]"
996,tt0001894,5,nm1413247,actor,\N,"[""A Fighter""]"
997,tt0001894,6,nm1413423,actor,\N,"[""The Referee""]"
998,tt0001894,7,nm0430865,actress,\N,\N
999,tt0001894,8,nm0001908,director,\N,\N

### `title.ratings.tsv` - Ratings
This table stores IMDb rating summary data for each rated title: `averageRating` and `numVotes`. It joins directly to `title.basics.tsv` on `tconst`, adding popularity and rating measures to the title records.

In [4]:
title_ratings = pd.read_csv('raw_data/title.ratings.tsv', sep='\t', nrows=1000, skiprows=10000, names=['tconst', 'averageRating', 'numVotes'])

In [28]:
title_ratings

        tconst  averageRating  numVotes
0    tt0024267            6.5        80
1    tt0024269            7.0       318
2    tt0024270            6.1        39
3    tt0024271            5.9        29
4    tt0024274            7.5        40
..         ...            ...       ...
995  tt0025605            6.0        81
996  tt0025606            6.7        84
997  tt0025607            5.9      1575
998  tt0025608            8.1        53
999  tt0025609            6.5       626

[1000 rows x 3 columns]